#pragma once
//GLOBAL UNIFORM BUFFERS -------------------------------------------------------------
/**
Buffer for storing 2D,3D and CUBE Textures.
Access indices with:
	TEXTURE_2D_0	-	TEXTURE_2D_100
	TEXTURE_3D_0	-	TEXTURE_2D_20
	TEXTURE_CUBE_0	-	TEXTURE_2D_20

Shader format:
layout(std140, binding = 0) uniform TextureBuffer
----	sampler2D textures2D[100];
----	sampler3D textures3D[20];
----	samplerCube texturesCube[20];
*/
#define TEXTURE_UNIFORM_BUFFER 0

//TEXTURE HANDLE OFFSET
#define TEXTURE_HANDLE_OFFSET 16
//Counts
#define TEXTURE_2D_COUNT	100
#define TEXTURE_3D_COUNT	20 
#define TEXTURE_CUBE_COUNT	20

//TEXTURE LOCATIONS
	#define TEXTURE_2D_0	0	*	TEXTURE_HANDLE_OFFSET
	#define TEXTURE_2D_1	1	*	TEXTURE_HANDLE_OFFSET
	#define TEXTURE_2D_2	2	*	TEXTURE_HANDLE_OFFSET
	#define TEXTURE_2D_3	3	*	TEXTURE_HANDLE_OFFSET
	#define TEXTURE_2D_4	4	*	TEXTURE_HANDLE_OFFSET
	#define TEXTURE_2D_5	5	*	TEXTURE_HANDLE_OFFSET
	#define TEXTURE_2D_6	6	*	TEXTURE_HANDLE_OFFSET
	#define TEXTURE_2D_7	7	*	TEXTURE_HANDLE_OFFSET
	#define TEXTURE_2D_8	8	*	TEXTURE_HANDLE_OFFSET
	#define TEXTURE_2D_9	9	*	TEXTURE_HANDLE_OFFSET
	#define TEXTURE_2D_10	10	*	TEXTURE_HANDLE_OFFSET
	#define TEXTURE_2D_11	11	*	TEXTURE_HANDLE_OFFSET
	#define TEXTURE_2D_12	12	*	TEXTURE_HANDLE_OFFSET
	#define TEXTURE_2D_13	13	*	TEXTURE_HANDLE_OFFSET
	#define TEXTURE_2D_14	14	*	TEXTURE_HANDLE_OFFSET
	#define TEXTURE_2D_15	15	*	TEXTURE_HANDLE_OFFSET
	#define TEXTURE_2D_16	16	*	TEXTURE_HANDLE_OFFSET
	//TODO(P3RK4N): FINISH		
								
	#define TEXTURE_3D_0	100	*	TEXTURE_HANDLE_OFFSET
	#define TEXTURE_3D_1	101	*	TEXTURE_HANDLE_OFFSET
	#define TEXTURE_3D_2	102	*	TEXTURE_HANDLE_OFFSET
	#define TEXTURE_3D_3	103	*	TEXTURE_HANDLE_OFFSET
	#define TEXTURE_3D_4	104	*	TEXTURE_HANDLE_OFFSET
	#define TEXTURE_3D_5	105	*	TEXTURE_HANDLE_OFFSET
	#define TEXTURE_3D_6	106	*	TEXTURE_HANDLE_OFFSET
	#define TEXTURE_3D_7	107	*	TEXTURE_HANDLE_OFFSET
	#define TEXTURE_3D_9	108	*	TEXTURE_HANDLE_OFFSET
	//TODO(P3RK4N): FINISH		
								
	#define TEXTURE_CUBE_0	120	*	TEXTURE_HANDLE_OFFSET
	#define TEXTURE_CUBE_1	121	*	TEXTURE_HANDLE_OFFSET
	#define TEXTURE_CUBE_2	122	*	TEXTURE_HANDLE_OFFSET
	#define TEXTURE_CUBE_3	123	*	TEXTURE_HANDLE_OFFSET
	#define TEXTURE_CUBE_4	124	*	TEXTURE_HANDLE_OFFSET
	#define TEXTURE_CUBE_5	125	*	TEXTURE_HANDLE_OFFSET
	#define TEXTURE_CUBE_6	126	*	TEXTURE_HANDLE_OFFSET
	#define TEXTURE_CUBE_7	127	*	TEXTURE_HANDLE_OFFSET
	#define TEXTURE_CUBE_9	128	*	TEXTURE_HANDLE_OFFSET
	//TODO(P3RK4N): FINISH

/**
Buffer for storing data that changes once per frame.
*/
#define PER_FRAME_UNIFORM_BUFFER 1
#define PER_FRAME_UNIFORM_BUFFER_SIZE 1000

/**
Buffer for storing data that changes with each model.
*/
#define PER_MODEL_UNIFORM_BUFFER 2
#define PER_MODEL_UNIFORM_BUFFER_SIZE 1000


#define UNIFORM_BUFFER_3	3
#define UNIFORM_BUFFER_4	4
#define UNIFORM_BUFFER_5	5
#define UNIFORM_BUFFER_6	6
#define UNIFORM_BUFFER_7	7
#define UNIFORM_BUFFER_8	8
#define UNIFORM_BUFFER_9	9
#define UNIFORM_BUFFER_10	10
#define UNIFORM_BUFFER_11	11
#define UNIFORM_BUFFER_12	12
#define UNIFORM_BUFFER_13	13
#define UNIFORM_BUFFER_14	14
#define UNIFORM_BUFFER_15	15

//------------------------------------------------------------------------------------
